### ISSUE TITLE
RecursionError with pyregion 1.2

### ISSUE THREAD

**Issue by cdeil** [astropy/pyregion#119]
It's been a while, but I needed to install `pyregion` again, and got this error:
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```
https://gist.github.com/cdeil/7b7a0e8287e911431343f6db5515d5bb

This has been fixed in the meantime, the dev version `pyregion-2.0.dev306` works fine.
I just wanted to make an issue to have a record for the issue, and to motivate another release.

@astrofrog - OK if I go ahead and make a new release now? See  #94 

I'm not advocating a lot of development for `pyregion` (agreed that should go to `regions`), but keeping it accessible by bug fixes and releases is good, no?

**Comment by astrofrog** [comment]
Please do make a release if you have time! It'd be good indeed to keep it at least functional.

**Comment by bsipocz** [comment]
That is because of the old astropy-helpers version and that it's not compatible with sphinx 1.6+.

So to fix that we either need to document that pyregions needs to be installed when sphinx is either not available, or it's <1.6, or do a new release. Or state that pyregions is abandoned and the version numbers of packages when it was last known to work.

**Comment by cdeil** [comment]
I have to go home now, but I have time to make a release tomorrow morning.
Probably we should do another `astropy-helpers` update before, even if master seems fine now, no?

**Comment by bsipocz** [comment]
OK, then if you can wait a few more days for the pyregions release, we've been already talking about making a new helpers release, so it may be worth waiting for it.

**Comment by astrofrog** [comment]
I don't know if there's anything in helpers 2.0.2 that would be needed here though, so not sure if worth delaying?

**Comment by bsipocz** [comment]
would the openmp have any positive effect on cython here?

**Comment by astrofrog** [comment]
No, we'd need to actually enable parallel mode in the Cython to see any effect.

**Comment by cdeil** [comment]
I'm closing this issue now. This was just to have a record in the issue tracker.
It's fixed in master and I'll make a release today or if I find any issues in the next days ( #94 is open to discuss).
