### ISSUE TITLE
Build error with gcc-14

### ISSUE THREAD

**Issue by olebole** [astropy/pyregion#165]
On Debian, pyregion now fails to build from source because of the standard use of gcc-14:
```
pyregion/_region_filter.c: In function ‘__pyx_pymod_exec__region_filter’:
pyregion/_region_filter.c:13000:3: error: returning ‘void *’ from a function with return type ‘int’ makes integer from pointer without a cast [-Wint-conversion]
13000 |   import_array();
      |   ^~~~~~~~~~~~
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```
This was reported as [Debian#1075410](https://bugs.debian.org/1075410).

If pyregion still has some future, I would try to fix this; however the last commit here was now 2 years ago (@larrybradley was the last committer); I have some doubts. Any advice?

**Comment by astrofrog** [comment]
Should be fixed in pyregion 2.3.0 (just released)
