### ISSUE TITLE
Functionality / examples for creatng and then writing region files

### ISSUE THREAD

**Issue by timstaley** [astropy/pyregion#22]
Hi Lee,
I'm looking for a way to create regions from scratch (e.g. representing results from a sourcefinder) and then write them to file. I see that the 'write to file' functionality was added some months back, but it's not clear to me how I'd create, rather than parse, region files. I'd be happy to have a go at adding this myself but wanted to ask if it's already in there somewhere, or if you think it would be easy to add?

On a tangent, I have another, slightly more philosophical question - in hindsight, do you think using pyparsing was worth it? It seems like clever stuff, but quite a lot of machinery to pull just to parse ds9 regions. But maybe that's just because I haven't got my head around it yet.

**Comment by cdeil** [comment]
@timstaley - It sounds to me like what you want is the new `regions` package:
http://astropy-regions.readthedocs.io/en/latest/getting_started.html

It allows you to create regions as Python / Astropy objects like this:
```python
>>> import regions
>>> reg = regions.CirclePixelRegion(center=regions.PixCoord(x=3, y=4), radius=5)
>>> print(reg)
CirclePixelRegion
center: PixCoord(x=3, y=4)
radius: 5
```

It also aims to do read / write for ds9. That's very limited at the moment, but this already works:
```
>>> regions.ds9_objects_to_string([reg])
'# Region file format: DS9 astropy/regions\nfk5\ncircle(3.0000,4.0000,5.0000)\n'
```

Side comment: The `ds9` parser in `regions` is just done using Python string and regex, no `pyparsing`. I think it remains to be seen if that was a good / better approach or not, it's also complex and not as complete as `pyregion` yet.

@timstaley - Would it be OK with you if we close this issue?

The idea is to focus development effort on `regions` now, and I'd prefer you try that out for your applications and file feature requests (or even pull requests) for things that are missing there.

**Comment by cdeil** [comment]
I'm closing this issue now.
See my last comment.

Maybe the `pyregion` docs could be improved by adding a section explaining this, but it's not essential. Pull requests welcome.
