### ISSUE TITLE
API for creating shapes and region files

### ISSUE THREAD

**Issue by astrodsg** [astropy/pyregion#27]
I just went though a process to create a *.reg file for ds9 using the pyregion file. I think that pyregion itself could have an improved API for creating these files. 

I saw on the [pyregion overview page](http://leejjoon.github.io/pyregion/users/overview.html) the method used was to define the string and then have it parsed by pyregion.parse

However, I created polygons (as an example shape) with set x,y points (shape parameters) using some other code and it seems it should be easy to create a Shape object or ShapeList using the name of the shape and the associated parameters then write out a *.reg file for ds9.
e.g.

    poly_xy = [(1,2),(2,3),(5,5),(0,4)]
    is_source = True # False ==> background
    properties = {'text':'poly1','color':'blue','tag':set(('group1','group2'))}
    shape = pyregion.Shape('polygon',poly_xy,is_source=is_source,**properties)

The local_attrs and global_attrs which are tuples of [],{} should probably be their own classes. i.e. 

    class Properties (object):
        def __init__ (self,*args,**kwargs):
             self.id_properties = list(args)
             self.properties = kwargs
             # check that all the keywords are appropriate 
             

then with many shapes you could create a shape_list. The ShapeList should probably have a `__setitem__` method which type checks that the objects being added are Shape objects. I think it'll prevent errors in methods such as ShapeList.write

If you could then set these:
* global_parameters : ShapeList should have a global_parameters method which can add global attributes. 
* coordsys : ShapeList.coordsys which in "PHYSICAL IMAGE FK4 B1950 FK5 J2000 GALACTIC ECLIPTIC ICRS LINEAR AMPLIFIER DETECTOR".split()

Then you can build up a ShapeList and write out a file which ds9 can read. 

I would do this on a forked version but I'm struggle to follow how to change the Shape object to be like this. The method for parsing the format is hard for me to parse. 

Cheers

**Comment by cdeil** [comment]
@astrodsg - Could you please have a look at this comment? https://github.com/astropy/pyregion/issues/22#issuecomment-236516591

Would closing this issue be OK with you?

(Please do file bug reports and feature requests on the `regions` tracker to help us prioritize development effort there. But I don't think anyone has plans to work on this in `pyregion`, which we plan to deprecate at some point, when the new `regions` package supports the same features and bugs have been shaken out.)

**Comment by cdeil** [comment]
I'm closing this now.

@astrodsg and all - Let's focus the discussion on #22 which is very similar.
