### ISSUE TITLE
Avoid duplication of functionality that can be done by Astropy

### ISSUE THREAD

**Issue by astrofrog** [astropy/pyregion#43]
Some of the functionality implemented in pyregion can be replaced by functionality in astropy. For example, ``region_numbers.py`` contains a lot of code for parsing and formatting of sexagesimal coordinates which could probably be replaced by ``Angle``.

**Comment by bsipocz** [comment]
This can be closed now that kapteyn is removed, isn't it?

**Comment by cdeil** [comment]
I'm closing this old issue now.

It's probably mostly implemented by #100.

@sargas or @astrofrog - If you still have any specific suggestions for things that can be improved in `pyregion` by re-using stuff from `astropy`, please re-open or file a new issue.
