### ISSUE TITLE
Fix Link in PIP

### ISSUE THREAD

**Issue by Knusper** [astropy/pyregion#55]
On https://pypi.python.org/pypi/pyregion/1.1.2 the link to the homepage is dead. Instead it should link here.

**Comment by souravsingh** [comment]
I think the homepage is not dead.I can access it

**Comment by cdeil** [comment]
This will be fixed once pyregion 1.2 is released in a few days (see #61).
Let's keep this issue open until the fix is in.

**Comment by cdeil** [comment]
We released pyregion 1.2 just now.
The links on PyPI are fixed: https://pypi.python.org/pypi/pyregion/1.2

Closing this issue now.
