### ISSUE TITLE
Changing properties of a region.

### ISSUE THREAD

**Issue by ivastar** [astropy/pyregion#56]
I'm using pyregion in an application where I read in a region file, change the size of the regions and then create a mask based on the new sizes. I found that there are two methods to change the size of the region (as well as all other properties): one through region.params and one through region.coord_list and the two methods don't talk to each other. The get_mask method only cares about the latter representation.

**Comment by cdeil** [comment]
FYI: `pyregion` has been mostly unmaintained for the past few years, and now we've started to work on a new [regions](http://astropy-regions.readthedocs.io/en/latest/) package based on Astropy. It doesn't contain code to compute masks yet, but that can be implemented by creating coordinate grids and calling `contains` like we do e.g. [here](https://gammapy.readthedocs.io/en/latest/api/gammapy.image.SkyImage.html#gammapy.image.SkyImage.region_mask). There's an open issue to add code to compute masks to `regions` here: https://github.com/astropy/regions/issues/55

@ivastar - Did you manage to get your analysis done? Do you still need an answer here?

My preference would be that we close this issue, and if you need something, we add it to the new `regions` package ASAP.

@ivastar - Thoughts?

**Comment by cdeil** [comment]
I'm closing this now.

@ivastar  - If you still have a question or feature request, please re-open or file a new issue!

**Comment by ivastar** [comment]
Yes, I did get my analysis done. I opened the issue just because I found this to be inconsistent.

**Comment by mcara** [comment]
@cdeil said: _"It doesn't contain code to compute masks yet, but that can be implemented by creating coordinate grids and calling ``contains`` like we do e.g..."_

I think that the capability to create masks from regions is a single most important feature of the old ``pyregion`` package. I cannot imagine ``pyregion`` without this feature (parsing a DS9 region file alone is quite useless for me).
