### ISSUE TITLE
Release v1.2

### ISSUE THREAD

**Issue by ViviCoder** [astropy/pyregion#61]
I am packaging pyregion for Debian.
The current version available on Pypi is quite old and does not contain the changes involving astropy.
Please consider releasing a new version of the package.

**Comment by cdeil** [comment]
I've added a 1.2 milestone and I'm changing the title of this issue to "Release v1.2".
We can use it to discuss issues / progress related to this release.

**Comment by cdeil** [comment]
I've gone through and assigned milestones to the issues.

Here's what's currently under "v0.2"
https://github.com/astropy/pyregion/milestone/1
(comments and changes welcome!)

I think it could happen in a day or two.

@leejjoon - Do you want to make the release or should I?

**Comment by leejjoon** [comment]
I will be more than happy you can make the release.
I am planning to augment #78 and and make a PR for #66. These should be simple changes, and I would expect I can do this later today.

**Comment by cdeil** [comment]
OK, I'll make the release this week when the issues / PRs under https://github.com/astropy/pyregion/milestone/1 are done.

@astrofrog - Can you please give me access to https://readthedocs.org/projects/pyregion/ so that I can add the stable version after the release?

**Comment by cdeil** [comment]
FYI: The "latest" build on readthedocs was from 2014.

I just now started a new build:
http://readthedocs.org/projects/pyregion/builds/4257500/

Looks like it worked just fine:
http://pyregion.readthedocs.io/en/latest/users/index.html
```
Release:	1.1.5.dev218
Date:	August 02, 2016
```

**Comment by cdeil** [comment]
FYI: The readthedocs webhook wasn't activated, that's why docs builds hadn't triggered in the past years. I activated it just now for this repo here: https://github.com/astropy/pyregion/settings/hooks

**Comment by bsipocz** [comment]
Is there a need for appveyor testing here?

**Comment by cdeil** [comment]
> Is there a need for appveyor testing here?

IMO yes, it would be great to have continuous testing on Windows to make sure everything's OK there.

**Comment by bsipocz** [comment]
Adding Appveyor is done in #88.

**Comment by cdeil** [comment]
The v1.2 milestone is all-clear now: https://github.com/astropy/pyregion/milestone/1
I'll make the v1.2 release now (or tonight latest) unless I hear any last-minute concerns here.

**Comment by cdeil** [comment]
I tried to follow http://docs.astropy.org/en/latest/development/affiliated-packages.html#releasing-an-affiliated-package and did this:
```
git clean -fdx
python setup.py build sdist --format=gztar
cd dist
tar zxvf pyregion-1.2.tar.gz
cd pyregion-1.2
python setup.py test
```
resulting in this error:
https://gist.github.com/cdeil/cdd92c4cb5bde653fca0ede7ae4dd320#file-gistfile1-txt-L676
```
E   ImportError: No module named 'pyregion._region_filter'
```

I see that `pyregion/_region_filter.c` is in the sdist tarball, but `pyregion/_region_filter.pyx` is missing, even though we have
```
recursive-include *.pyx *.c *.pxd
```
in https://github.com/astropy/pyregion/blob/master/MANIFEST.in#L10

@astrofrog @bsipocz - Any idea what the issue and fix is for this problem?

**Comment by cdeil** [comment]
When running from the git source folder, it works as it should:
```
cythoning pyregion/_region_filter.pyx to pyregion/_region_filter.c
building 'pyregion._region_filter' extension
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c pyregion/_region_filter.c -o build/temp.macosx-10.11-x86_64-3.5/pyregion/_region_filter.o -Wp,-w -Wno-unused-function
/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names build/temp.macosx-10.11-x86_64-3.5/pyregion/_region_filter.o -o build/lib.macosx-10.11-x86_64-3.5/pyregion/_region_filter.cpython-35m-darwin.so
copying pyregion/cython_version.py -> build/lib.macosx-10.11-x86_64-3.5/pyregion
```
https://gist.github.com/cdeil/cdd92c4cb5bde653fca0ede7ae4dd320#file-gistfile1-txt-L76

@bsipocz - Do you have time to add a travis-ci build that checks that tests from sdist pass, so that this keeps working going forward?

**Comment by bsipocz** [comment]
I have no idea. 
However just spotted that line should have include the package name I think (it does in astropy and photutils, but not in the template).

```
recursive-include pyregion *.pyx *.c *.pxd
```

**Comment by cdeil** [comment]
@bsipocz - Thanks for the tip. 😄 

Changing to
```
recursive-include pyregion *.pyx *.c *.pxd
```
fixes the issue.

I have to go now, but I'll do the release tonight.

**Comment by bsipocz** [comment]
@cdeil - Glad to hear it, I'm opening a PR for the template to fix this. Also in that this is fixed now with something unrelated to pyregion, I think no need to add the extra test to travis.

**Comment by cdeil** [comment]
Release sdist is here: https://pypi.python.org/pypi/pyregion/1.2
Tag is here: https://github.com/astropy/pyregion/tree/1.2

@astropy/regions-developers - Please try v1.2 and report any install issues or test fails here (if any).

@bsipocz - Could you make the conda package?

**Comment by cdeil** [comment]
@ViviCoder wrote

> I am packaging pyregion for Debian. The current version available on Pypi is quite old and does not contain the changes involving astropy. Please consider releasing a new version of the package.

My suggestion would be that you wait a few weeks for `pyregion` 2.0. There #54 will be merged, and we will just use Astropy, no longer bundle files from Kapteyn with a different license. That should simplify Debian packaging.
Is there a short-term deadline on the Debian packaging side to get pyregion 2.0 into an upcoming release?

**Comment by cdeil** [comment]
@astrofrog - Please add me ("deil") on RTD for pyregion, so that I can do admin stuff like adding v1.2. http://readthedocs.org/projects/pyregion/

**Comment by bsipocz** [comment]
> @bsipocz - Could you make the conda package?

@cdeil - Done once https://github.com/astropy/conda-channel-astropy/pull/69 is merged.

**Comment by cdeil** [comment]
Just a note to self: to finish off the 1.2 release and close this issue, these things should happen first:
- [ ] add v1.2 on RTD here:  http://readthedocs.org/projects/pyregion/
- [ ] sort out pyregion conda package issues, see https://github.com/astropy/conda-channel-astropy/pull/69

**Comment by cdeil** [comment]
v1.2 docs are now available here: http://pyregion.readthedocs.io/en/1.2/

**Comment by bsipocz** [comment]
Closing this issue as the conda package is also done.

**Comment by cdeil** [comment]
@bsipocz - Thanks.

Just to confirm: this works for me on OS X:
```
conda install -c astropy pyregion
python -c 'import pyregion; pyregion.test()'
# 18 tests passed
```
