### ISSUE TITLE
Conda conflict pyregion and numpy 1.11

### ISSUE THREAD

**Issue by MSeifert04** [astropy/pyregion#68]
I don't know if that's a problem with something on `conda` or how the package was build for conda but nevertheless `pyregion` prohibits me to update `numpy` to 1.11.

Maybe that's something trivial someone could alter or is there a specific reason not to support numpy 1.11?

```
[Anaconda] C:\Users\Admin>conda install numpy=1.11
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - astroscrappy (target=astroscrappy-1.0.3-np110py35_0.tar.bz2) -> numpy 1.10*|1.9*
  - astroscrappy (target=astroscrappy-1.0.3-np110py35_0.tar.bz2) -> python 2.7*|3.4*
  - numpy 1.11*
  - pyregion (target=pyregion-1.1.4-np110py35_0.tar.bz2) -> numpy 1.10*|1.6*|1.7*|1.8*|1.9*
  - pyregion (target=pyregion-1.1.4-np110py35_0.tar.bz2) -> python 2.7*|3.4*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by bsipocz** [comment]
@MSeifert04 - There are quite a few outstanding PRs, and also a note in the conda recipe that the next release would remove the numpy dependency in the conda packages. 

However as far as I see pyregion is not actively maintained (there are quite a few pending PRs and issues, etc). So I would suggest to remove the conda package, update numpy to 1.11 and then pip install pyregion.

Also look out for the new https://github.com/astropy/regions package.

**Comment by MSeifert04** [comment]
@bsipocz Thank you! I make sure I checkout this regions package. Unfortunatly there seems to not much documentation (yet).

**Comment by bsipocz** [comment]
It's very much work-in-progress, there hasn't been any release yet either.

**Comment by bsipocz** [comment]
@MSeifert04 - I believe this must be solved now, could you please confirm?

**Comment by MSeifert04** [comment]
> I believe this must be solved now, could you please confirm?

I don't use this package anymore but yes I could install it without dependency conflicts :+1:
